# Generated by Django 2.0 on 2021-04-05 16:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('lable', models.CharField(choices=[('iboss', '一级boss'), ('channel', '渠道'), ('interface', '短厅'), ('other', '其他'), ('tocol', '协议')], default=None, max_length=32, verbose_name='模块')),
                ('brief_content', models.TextField(blank=True, verbose_name='摘要')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
