# Generated by Django 2.0 on 2019-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lable',
            field=models.CharField(choices=[('iboss', '一级boss'), ('channel', '渠道'), ('interface', '短厅'), ('other', '其他')], default=None, max_length=6, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
    ]
